### ISSUE TITLE
Support for older versions of Laminas

### ISSUE THREAD

**Issue by brockcaldwell** [laminas/laminas-mvc-skeleton#33]
This may or may not be the right place for this question, so I apologize if it's not.  I need to know if there is a way to use this tool to downlad a skeleton application for an older version Zend/Laminas MVC.  I need a version of Zend/Laminas that supports PHP 5.6 (I know it's old but we have a contract for LTS) which I believe takes me back to the middle of v2.

Thanks!

**Comment by weierophinney** [comment]
In that case, you'll want to use the original Zend Framework MVC skeleton, and do a Laminas migration from there. Fortunately, the last version of ZF's skeleton (3.1.3) still supported PHP 5.6.

As an example:

```console
$ composer create-project zendframework/skeleton-application project-name
# does some work, prompts you to install some features, etc.
$ cd project-name
# Set the project target PHP version, to prevent updates to package versions that do not support it:
$ composer config platform.php 5.6.40
# perform Laminas migration here
```

For that last step, see [our migration documentation](https://docs.laminas.dev/migration/).

We migrated all historical versions of each component, so this will keep you on those versions originally installed; the PHP platform configuration ensures you stay on versions that support PHP 5.6 as well.

**Comment by brockcaldwell** [comment]
Awesome! Thank you so much!
