### ISSUE TITLE
Update docker-compose file to latest specifications 

### ISSUE THREAD

**Issue by eduardobona** [laminas/laminas-mvc-skeleton#43]
### Feature Request

The project's docker-compose file works but is different from the specifications desired by the official Docker documentation. Two updates would be required using Services and - if possible - changing the file name. 

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | no
| BC Break    | no

#### Summary

Keeping the docker file within the expected specifications will prevent future breakpoints in the execution of containers.

Doc:

> The Compose file is a YAML file defining version (DEPRECATED), services (REQUIRED), networks, volumes, configs and secrets. The default path for a Compose file is compose.yaml (preferred) or compose.yml in working directory. Compose implementations SHOULD also support docker-compose.yaml and docker-compose.yml for backward compatibility. If both files exist, Compose implementations MUST prefer canonical compose.yaml one.

https://docs.docker.com/compose/compose-file/

Actions:
- First, use Services (required) in a top document
- Rename file to compose.yaml or compose.yml

**Comment by pgrafe** [comment]
Hi,

+1 from me. Could be a littlebit frustrating for new users who want to checkout laminas with docker.

Here it seems to be fixed already:
https://github.com/laminas/getlaminas.org

**Comment by Ocramius** [comment]
Handled in #52
