### ISSUE TITLE
inlineScript helper echoed twice in layout.phtml

### ISSUE THREAD

**Issue by wotent** [laminas/laminas-mvc-skeleton#8]
### Bug Report

There are two `<?= $this->inlineScript(); ?>` in `layout.phtml`.
One is before `</head>`, prepending bootstrap and jquery scripts.
The other is right before `</body>` .

#### Summary

inlineScript helper echoed twice in layout.phtml

#### Current behavior

jquery.js and bootstrap.js appeared twice in browser

#### How to reproduce

Install plain skeleton

#### Expected behavior

I don't know if this behavior is intended or a mistake.
The former `inlineScript` used to be `headScript`, in commit [Bootstrap updated to the latest version - 4.0.0](https://github.com/zendframework/ZendSkeletonApplication/commit/534614cdca703b5e2f354e77c68eee2410bc1f69) it was changed to `inilneScript`.

**Comment by froschdesign** [comment]
It is a mistake. In the `head` the `headScript` helper must be used and the scripts for jQuery and Bootstrap must be added to the `inlineScript` helper [right before the closing `</body>` tag](https://getbootstrap.com/docs/4.4/getting-started/introduction/#js).
